spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hoaxify
    username: root
    password: root
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  profiles:
    active:
      - dev
---
spring:
  profiles: prod
  datasource:
    # jdbc url for mysql db
    url: jdbc:mysql://localhost:3306/hoaxify
    username: root
    password: root
    # and to such your entities with database
    jpa:
      hibernate:
        ddl-auto: create
  mysql:
    console:
      enabled: false
hoaxify:
  upload-path: uploads-prod
---
spring:
  profiles: dev
  datasource:
    url:jdbc:mysql://localhost:3306/hoaxify-dev
hoaxify:
  upload-path: uploads-dev
---
spring:
  profiles: test
hoaxify:
  upload-path: uploads-test